apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics
  namespace: victoria   # отдельный namespace
spec:
  interval: 1m
  chart:
    spec:
      chart: victoria-metrics-k8s-stack
      sourceRef:
        kind: HelmRepository
        name: victoria-metrics
        namespace: flux-system
      version: 0.59.4
  releaseName: vm-stack
  values:
    fullnameOverride: vm-stack
    standalone:
      enabled: true        # только один pod VictoriaMetrics
      retentionPeriod: 30d
    grafana:
      enabled: true
      adminUser: admin
      adminPassword: changeme
      ingress:
        enabled: true
        hosts:
          - grafana.demo
        ingressClassName: nginx
