apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vm
  namespace: monitoring
spec:
  interval: 1m
  releaseName: vm
  chart:
    spec:
      chart: victoria-metrics-k8s-stack
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: victoria-metrics
        namespace: flux-system
  values:
    vmsingle:
      enabled: true
      replicaCount: 1
      resources:
        requests:
          cpu: 200m
          memory: 512Mi
      persistentVolume:
        enabled: true
        size: 1Gi   # здесь 1Гб
        storageClassName: longhorn

    vmcluster:
      enabled: false

    grafana:
      enabled: true
      ingress:
        enabled: true
        ingressClassName: nginx
        hosts:
          - grafana.demo
        tls: []
      adminUser: admin
      adminPassword: admin
      persistence:
        enabled: true
        size: 1Gi   # тоже 1Гб
        storageClassName: longhorn

    vmagent:
      replicaCount: 1
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
