apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: harbor
  namespace: default
spec:
  interval: '1m0s'
  chart:
    spec:
      chart: harbor
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: flux-system
      version: "1.17.2"
  values:
    expose:
      type: ingress
      tls:
        enabled: false
      ingress:
        className: nginx
        hosts:
          core: harbor.demo
    externalURL: http://harbor.demo
    harborAdminPassword: "supersecretpassword"
    persistence:
      enabled: true
      persistentVolumeClaim:
        registry:
          size: 5Gi
          storageClass: longhorn
        jobservice:
          size: 1Gi
          storageClass: longhorn
        database:
          size: 1Gi
          storageClass: longhorn
        redis:
          size: 1Gi
          storageClass: longhorn
        trivy:
          size: 2Gi
          storageClass: longhorn
      harborUsers:
      - name: developer
        password: "developer"
        email: "dev@example.com"
        realname: "Dev User"
        sysadmin: false
